PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK {
  ex:b a dcat:Dataset ;
    dcat:distribution ex:d .
  ex:d a dcat:Distribution ;
    dcterms:title "Distribution D" ;
    dcat:accessURL <http://example.com/d/download> ;
    dcat:accessService ex:c .
  OPTIONAL {
    ex:c a ?o .
  }
  FILTER ( !bound(?o) )
}