PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK {
  ex:a a dcat:Catalog .
  FILTER NOT EXISTS { ex:a dcat:service ?o }
  FILTER NOT EXISTS { ex:c ?p ?o }
}
